FROM golang:1.17 as test-api
ENV CGO_ENABLED 0 
ARG BUILD_REF

COPY . /src
WORKDIR /src
RUN go build -ldflags "-X main.build=${BUILD_REF}" -o service

FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=test-api /src/service /service/service
WORKDIR /service
CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
        org.opencontainers.image.title="test-api" \
        org.opencontainers.image.authors="Umed Jadhav <umedj.formal@gmail.com" \
        org.opencontainers.image.source="https://github.com/umedj/cnGoService/" \
        org.opencontainers.image.revision="${BUILD_REF}" \
        org.opencontainers.image.vendor="Umed Jadhav"
